accounts/urls.py
from django.contrib import admin # noqa
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountDeleteView

app_name = 'accounts'
urlpatterns = [

    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordChangeView.as_view(), name='password'),
    path('delete', AccountDeleteView.as_view(), name='profile_delete')
    # path('update/<int:student_id>', StudentUpdateView.as_view(), name='update'),
    # path('delete/<int:student_id>', StudentDeleteView.as_view(), name='delete'),

]

lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import index

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('classroom/', include('classroom.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('', index, name='index')
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from PIL import Image

from django.contrib.auth.models import User
from django.db import models  # noqa


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        to=User,  # settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    image = models.ImageField(null=True, default='default.jpg', upload_to='pics/')
    interests = models.CharField(max_length=128, null=True)

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

from accounts.models import Profile


class AccountRegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        fields = ['username', 'first_name', 'last_name', 'email']


class AccountProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'interests']

accounts/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.edit import ProcessFormView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm, AccountProfileUpdateForm


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f"User {form.cleaned_data['username']} has succesfully created")
        return result


class AccountLoginView(LoginView):
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f"User {self.request.user} has succesfully logged in")
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logged_out.html'

    def dispatch(self, request, *args, **kwargs):
        messages.info(self.request, f"User {self.request.user} has succesfully logged out")
        return super().dispatch(request, *args, **kwargs)


# class AccountUpdateView(UpdateView):
#     model = User
#     template_name = 'profile.html'
#     success_url = reverse_lazy('index')
#     form_class = AccountUpdateForm
#
#     def get_object(self, queryset=None):
#         return self.request.user
#
#     def form_valid(self, form):
#         result = super().form_valid(form)
#         messages.success(self.request, f" Profile: User {self.request.user} has succesfully updated")
#         return result


class AccountPasswordChangeView(PasswordChangeView):
    template_name = 'password_change.html'
    success_url = reverse_lazy('index')


class AccountUpdateView(ProcessFormView):

    def get(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(instance=user)
        profile_form = AccountProfileUpdateForm(instance=profile)

        return render(
            request=request,
            template_name='profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form,
            }
        )

    def post(self, request, *args, **kwargs):
        user = self.request.user
        profile = self.request.user.profile

        user_form = AccountUpdateForm(
            data=request.POST,
            instance=user
        )
        profile_form = AccountProfileUpdateForm(
            data=request.POST,
            files=request.FILES,
            instance=profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('accounts:profile'))

        return render(
            request=request,
            template_name='profile.html',
            context={
                'user_form': user_form,
                'profile_form': profile_form,
            }
        )


class AccountDeleteView(ProcessFormView):
    def get(self, request, *args, **kwargs):
        user = self.request.user

        return render(request,
                      template_name='profile:delete.html',
                      context={'user': user}
                      )

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user.delete()

        return render(request,
                      template_name='index.html',
                      context={'user': user}
                      )

accounts/templates/logged_out.html
{% extends 'base.html' %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">User is logged out</h1>
{% endblock %}

{% block main %}
    <div class="d-grid gap-2 col-4 mx-auto">
        <a href="{% url 'accounts:login' %}" class="btn btn-primary" type="button">Login</a>
        <a href="{% url 'accounts:registration' %}" class="btn btn-success" type="button">Register</a>
    </div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Login as user</h1>
{% endblock %}

{% block main %}

    <div class="container-xxl">



            <form method='post' class="form-control bg-light" style="margin-top:30px;">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg" style="margin-top:10px">Login</button>

            </form>

    </div>
{% endblock %}

accounts/templates/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Change password</h1>
{% endblock %}

{% block main %}

    <div class="container-xxl">



            <form method='post' class="form-control bg-light" style="margin-top:30px;">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg" style="margin-top:10px">Submit</button>

            </form>

    </div>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Update Profile</h1>
{% endblock %}

{% block main %}
    <div class="container">
             <form method='post' enctype="multipart/form-data">
                  {% csrf_token %}

                    <div class="media">
                        <div class="img-circle.vert">
                            <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.profile.image.url }}">
                        </div>
                        <div class="media-body  p-3 m-3">
                            <h2 class="account-heading">{{ user.username }}</h2>
                            <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                            <p class="text-secondary">{{ user.email }}</p>
                        </div>
                    </div>


                  {{user_form|crispy}}
                  {{profile_form|crispy}}

                  <input class="btn btn-success btn-lg mt-2" type="submit" value="Save">
                    <a class="btn btn-danger btn-lg mt-2" href="{% url 'accounts:profile_delete'  %}" role="button">Delete</a>
             </form>

    </div>
{% endblock %}

accounts/templates/profile:delete.html
{% extends 'base.html' %}

{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Delete profile</h1>
{% endblock %}

{% block main %}
    <div class="container-xxl" style="text-align: center">

        <h3> Do you really want to delete Profile: {{user.username}} ? </h3>

        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger btn-lg mt-2" type="submit" value="Delete">
            <a class="btn btn-warning btn-lg mt-2" href="{% url 'accounts:profile'  %}" role="button">Cancel</a>
        </form>

    </div>
{% endblock %}

accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block greetings %}
    <h1 class="display-1"  style="text-align:center; color:red;">Create account</h1>
{% endblock %}

{% block main %}

    <div class="container-xxl">



            <form method='post' class="form-control bg-light" style="margin-top:30px;">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg" style="margin-top:10px">Create</button>

            </form>

    </div>
{% endblock %}