accounts/urls.py
from django.contrib import admin # noqa
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountDeleteView

app_name = 'accounts'
urlpatterns = [

    path('registration', AccountRegistrationView.as_view(), name='registration'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordChangeView.as_view(), name='password'),
    path('delete', AccountDeleteView.as_view(), name='profile_delete')
    # path('update/<int:student_id>', StudentUpdateView.as_view(), name='update'),
    # path('delete/<int:student_id>', StudentDeleteView.as_view(), name='delete'),

]

lms/urls.py
import debug_toolbar

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from core.views import index

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('classroom/', include('classroom.urls')),
    path('courses/', include('courses.urls')),
    path('accounts/', include('accounts.urls')),
    path('', index, name='index')
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import random

from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from faker import Faker

from core.validators import validate_prohibited_email, validate_phone_number


# Create your models here.
class Person(models.Model):
    class Meta:
        abstract = True

    first_name = models.CharField(max_length=64, null=False)
    last_name = models.CharField(max_length=84, null=False)
    age = models.IntegerField(null=True, default=42, validators=[
        MinValueValidator(10),
        MaxValueValidator(100),
    ])

    email_field = models.EmailField(max_length=64, default="email.com", validators=[
        validate_prohibited_email
    ])
    phone_number = models.CharField(null=False, max_length=20, default='', validators=[
        validate_phone_number
    ])

    def __str__(self):
        return f'{self.first_name}, {self.last_name}, {self.age},' \
               f' {self.email_field}, {self.phone_number}'

    @classmethod
    def _generate(cls):
        faker = Faker()
        object = cls( # noqa
            first_name=faker.first_name(),
            last_name=faker.last_name(),
            age=random.randint(15, 105)
        )
        object.save()
        return object

    @classmethod
    def generate(cls, count):
        for _ in range(count):
            cls._generate()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'


class Logger(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    path = models.CharField(max_length=128)
    create_date = models.DateTimeField(auto_now_add=True)
    execution_time = models.FloatField()
    query_params = models.CharField(max_length=64, null=True)
    info = models.CharField(max_length=128, null=True)

core/views.py
from django.shortcuts import render  # noqa


# Create your views here.
def index(request):
    return render(request,
                  template_name='index.html')

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossorigin="anonymous">

    <title>LMS</title>
</head>
<body>

<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <div class="container-fluid" style="margin-left:50px">
        <a class="navbar-brand" href="{% url 'index' %}">LMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'list' %}">Students</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'groups_list' %}">Groups</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'list_teachers' %}">Teachers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'classrooms_list' %}">Classrooms</a>
            </li>
              <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'courses_list' %}">Courses</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>

            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
           {% if user.is_authenticated %}
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <div class="img-circle">
                  <img class="rounded-circle" width="40" height="40"  src="{{ user.profile.image.url }}">
                </div>
                 <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                </li>
                 <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
            {% else %}

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:registration' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
              </li>
             </ul>
          {% endif %}

        </div>
      </div>
    </nav>

    {% include 'includes/messages.html' %}
    {% block greetings %}

        <h1 class="display-1">Current operation is:</h1>

    {% endblock %}

        {% block main %}


        <h1 style="text-align:center">Welcome to LMS!</h1>

    {% endblock %}

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}

{% block greetings %}
    <div class="container mt-3" style="border-style:dotted;  border-width:2px;">
        <h1 style="text-align:center; font-size:300%; color:red;">WELCOME TO LMS!</h1>
    </div>
{% endblock %}

{% block main %}

{% endblock %}